version: "3"

services:
  project-service:
    build:
      context: ./../
      dockerfile: ./Dockerfile
    ports:
      - 8083:8083
    environment:
      APP_ENV: production
    networks:
      lsu_network:
        ipv4_address: 192.168.0.8

networks:
  lsu_network:
    external: true
